version: '3.8'

services:

  db:
    image: mariadb:10.3.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sami6070
    ports:
      - 127.0.0.1:3308:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: