field: e4414be5-ec53-440a-b818-1a381e65c433 # Nav Link
fieldLayouts:
  84d693b2-0565-4309-a8c5-914f5cad5df1:
    tabs:
      -
        elements:
          -
            fieldUid: 9353bfe0-77ec-4c96-afc1-3cc85bc6959b # Link Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bf6b89d9-e068-4a04-9f43-1a7a2d42bd79 # Link Destination
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9353bfe0-77ec-4c96-afc1-3cc85bc6959b: # Link Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bf6b89d9-e068-4a04-9f43-1a7a2d42bd79: # Link Destination
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkDestination
    instructions: ''
    name: 'Link Destination'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Wählen Sie eine Seite aus'
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: link
name: Link
sortOrder: 1
