fieldLayouts:
  5e11f49e-9998-4e46-8d6f-ccf733002e7c:
    tabs:
      -
        elements:
          -
            fieldUid: af236ed7-2045-4ee4-b6c9-fa700fec2aae # seo Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 42fda29a-485e-47ea-8f31-8d3f398a7b6d # seo Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 1
handle: gutscheine
hasTitleField: false
name: Gutscheine
section: af2f78ad-694f-4f2c-9c6f-a24a5297b71e # Gutscheine
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
