columnSuffix: null
contentColumnType: string
fieldGroup: cc7d01e7-6d4f-4329-8f74-68b700b031d0 # Gutschein Section
handle: gutscheinImage
instructions: ''
name: 'Gutschein Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:5cce6b80-a35c-4207-82e0-3940c9091376' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: 'Bild von Gutschein hinzufügen'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:5cce6b80-a35c-4207-82e0-3940c9091376' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:5cce6b80-a35c-4207-82e0-3940c9091376' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
