columnSuffix: iqfuadci
contentColumnType: text
fieldGroup: cc7d01e7-6d4f-4329-8f74-68b700b031d0 # Gutschein Section
handle: gutscheinText
instructions: ''
name: 'Gutschein Text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
