columnSuffix: zevnqzav
contentColumnType: text
fieldGroup: 1e51ec97-9959-4860-8d78-a37833c6a526 # Common
handle: h2TitlePrice
instructions: ''
name: 'h2 Title Price Section'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Hier eine Überschrift'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
