columnSuffix: null
contentColumnType: string
fieldGroup: 09faf330-8a6d-43fb-8902-634963e2b596 # Cards
handle: prices
instructions: ''
name: Prices
searchable: false
settings:
  contentTable: '{{%matrixcontent_prices}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
