columnSuffix: null
contentColumnType: string
fieldGroup: f935160c-f13f-4345-a1b2-964ccaf23ef6 # Slider Content
handle: sliderTexts
instructions: ''
name: 'Slider Texts'
searchable: false
settings:
  contentTable: '{{%matrixcontent_slidertexts}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
