columnSuffix: qdzgebkt
contentColumnType: text
fieldGroup: 9eb431c5-7fe6-4c45-be5d-6c94ade7993e # Assets
handle: telefonnummer
instructions: ''
name: Telefonnummer
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: Telefonnummer
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
