fieldLayouts:
  ec5f9538-4f3f-4803-871e-1d8d782a56fe:
    tabs:
      -
        elements:
          -
            fieldUid: 1bf39833-e1d7-47ad-8cec-0e5f634ecfeb # Gutschein Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7e3b3ae6-f422-47dc-96c7-602eef92f190 # Gutschein Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Gutscheine
        sortOrder: 1
handle: gutscheine
name: Gutscheine
sortOrder: 4
