defaultPlacement: end
enableVersioning: true
handle: kontakt
name: Kontakt
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d0b81f54-9f0b-47ff-8b70-ede217a82e9d: # voi-entspannt
    enabledByDefault: true
    hasUrls: true
    template: _pages/pages/contact.twig
    uriFormat: kontaktiere-mich
type: single
